[package]
name = "jack_recorder"
version = "0.1.0"
edition = "2021"
authors = ["Miha Valencic"]
description = "JACK audio recorder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.12", features = ["derive"] }
jack = "0.8"
ctrlc = { version = "3.0", features = ["termination"] }